projects:
  todo:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: ap-northeast-2
        apiId: ogg2zwvfcramnestmwartz5txq
        maxDepth: 2
extensions:
  amplify:
    version: 3
